import './globals.css'
import localFont from 'next/font/local'
import type { Metadata } from 'next'
 
const publicSans = localFont({
  src: './PublicSans.woff2',
  display: 'swap',
  variable: '--font-public-sans'
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={publicSans.variable}>{children}</body>
    </html>
  )
}
